spring.application.name=mediatracker
spring.datasource.url=jdbc:sqlite:tracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.tool.schema=DEBUG
logging.level.root=INFO

#server.address=0.0.0.0

mal.api.base-url=https://api.myanimelist.net/v2
mal.site.base-url=https://myanimelist.net
mal.api.client-id=${MAL_CLIENT_ID}
placeholderImage.url=https://placehold.co/100x100?text=No+Image

